# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Logseq Publish 🚩
        uses: logseq/publish-spa@v0.3.1
        # with:
        #   graph-directory: DevOpsNotes

      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      
      - name: Add Google Verification
        run: |
          echo 'google-site-verification: google95599d807a6231ed.html' >> $GITHUB_WORKSPACE/www/google95599d807a6231ed.html   

      - name: Add robots.txt
        run: |
          echo 'User-agent: *' >> $GITHUB_WORKSPACE/www/robots.txt
          echo 'Allow: /' >> $GITHUB_WORKSPACE/www/robots.txt
          echo 'Sitemap: https://pofengliu.github.io/devops-notes/sitemap.xml' >> $GITHUB_WORKSPACE/www/robots.txt
  
      - name: Add SEO Meta Tags
        run: |
          echo '<meta name="description" content="DevOps Task-Force Blog">' >> $GITHUB_WORKSPACE/www/index.html
          echo '<meta name="keywords" content="devops, platform engineering, sbe">' >> $GITHUB_WORKSPACE/www/index.html

      - name: Generate Sitemap
        run: |
          # 这里可以使用一个工具生成 sitemap.xml
          echo '<?xml version="1.0" encoding="UTF-8"?>' > $GITHUB_WORKSPACE/www/sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> $GITHUB_WORKSPACE/www/sitemap.xml
          cat <<EOL >> $GITHUB_WORKSPACE/www/sitemap.xml
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/about%20us</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/effective%20code%20review</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/devops%E5%8D%81%E5%B9%B4%E4%BA%86%EF%BC%8C%E4%BD%A0%EF%BC%8C%E6%83%B3%E6%94%B9%E8%AE%8A%E4%BA%86%E5%97%8E%3F</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/devops%20%E8%AE%8A%E9%9D%A9%E5%9B%B0%E5%B1%80%E8%88%87%E5%B9%B3%E5%8F%B0%E5%B7%A5%E7%A8%8B</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/%E5%AF%A6%E4%BE%8B%E5%8C%96%E9%9C%80%E6%B1%82%20(specification%20by%20example)</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/%E9%96%8B%E7%99%BC%E6%B5%81%E7%A8%8B%E7%9A%84%E5%85%B1%E8%AD%98%E8%88%87%E7%9B%AE%E6%A8%99</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/tech%20planning%20with%20community</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/%E5%88%B0%E5%BA%95%E6%96%87%E5%8C%96%E9%87%8D%E8%A6%81%E9%82%84%E6%98%AF%E6%8A%80%E8%A1%93%E5%84%AA%E5%85%88</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/%E4%BB%80%E9%BA%BC%E6%98%AF%E8%87%AA%E5%8B%95%E5%8C%96%E6%B8%AC%E8%A9%A6%E7%9A%84%E6%A8%99%E7%9A%84%EF%BC%9F</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/%E8%BB%9F%E9%AB%94%E9%96%8B%E7%99%BC%E5%88%B0%E5%BA%95%E6%98%AF%E8%A6%81%E5%BF%AB%E4%BB%80%E9%BA%BC</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/community%20driven%20devops</loc></url>
          <url><loc>https://pofengliu.github.io/devops-notes/#/page/%E5%9B%9E%E9%A1%A7%202023</loc></url>
          EOL
          echo '</urlset>' >> $GITHUB_WORKSPACE/www/sitemap.xml
  
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
          clean: true
          single-commit: true
